// catalogsource.go — Forge implements catalogdomain.CatalogSource so
// app/catalog can include forges in the system-prompt summary. Per
// catalog.md §12: forges are PerItem (generator may freely group /
// merge into "5 CSV-processing forges"-style descriptions).
//
// Forge description comes from the Forge.Description field (stored at
// create-time, often LLM-generated by the create_forge tool); empty
// descriptions fall back to the JSON tags array as a hint string so
// the catalog never shows a blank entry.
//
// catalogsource.go ——Forge 实现 catalogdomain.CatalogSource 让 app/catalog
// 把 forge 纳入 system-prompt summary。catalog.md §12：forge 是 PerItem
// （generator 可自由分组合并为 "5 个 CSV 处理 forge" 风格描述）。
//
// Forge description 来自 Forge.Description 字段（创建时存，常为 create_forge
// 工具 LLM 生成）；空 description 退化为 tags JSON 数组拼接 hint。
package forge

import (
	"context"
	"strings"

	catalogdomain "github.com/sunweilin/forgify/backend/internal/domain/catalog"
)

// AsCatalogSource returns the CatalogSource port adapter for this Service.
// main.go calls this once at boot and registers the result with
// catalogapp.Service.RegisterSource.
//
// AsCatalogSource 返本 Service 的 CatalogSource port 适配器。main.go 在
// boot 调一次 + 把结果注册到 catalogapp.Service.RegisterSource。
func (s *Service) AsCatalogSource() catalogdomain.CatalogSource {
	return &forgeCatalogSource{svc: s}
}

type forgeCatalogSource struct {
	svc *Service
}

func (c *forgeCatalogSource) Name() string                           { return "forge" }
func (c *forgeCatalogSource) Granularity() catalogdomain.Granularity { return catalogdomain.PerItem }

func (c *forgeCatalogSource) ListItems(ctx context.Context) ([]catalogdomain.Item, error) {
	forges, err := c.svc.ListAll(ctx)
	if err != nil {
		return nil, err
	}
	items := make([]catalogdomain.Item, 0, len(forges))
	for _, f := range forges {
		desc := strings.TrimSpace(f.Description)
		if desc == "" {
			// Fall back to tags so catalog generator has SOMETHING to
			// describe the forge with. Tags is a JSON-stringified array
			// in storage; we strip the brackets + quotes to make it
			// readable in the prompt rather than parsing it (Generator
			// reads description as opaque text — no schema needed).
			// 退化到 tags 让 generator 有内容可描述。Tags 是 JSON 数组字符
			// 串；剥括号+引号让 prompt 可读，不解析（Generator 视
			// description 为不透明文本）。
			desc = simplifyTagsJSON(f.Tags)
		}
		if desc == "" {
			desc = "(no description)"
		}
		items = append(items, catalogdomain.Item{
			Source:      "forge",
			ID:          f.ID,
			Name:        f.Name,
			Description: desc,
		})
	}
	return items, nil
}

// simplifyTagsJSON converts a JSON array string `["csv","data"]` to the
// human-readable `csv, data`. On parse failure (shouldn't happen since
// the column has a default of `[]`) returns the raw input unchanged.
//
// simplifyTagsJSON 把 JSON 数组串 `["csv","data"]` 变可读 `csv, data`。
// parse 失败（不该——列有 `[]` 默认）返原样。
func simplifyTagsJSON(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" || raw == "[]" {
		return ""
	}
	// Cheap manual strip: works for the canonical `["a","b"]` shape the
	// store always produces. Skip the json.Unmarshal round-trip — this
	// is just a fallback display string.
	// 廉价手剥：覆盖 store 永远产出的 `["a","b"]` 规范形。跳 json.Unmarshal
	// ——这只是 fallback 展示串。
	stripped := strings.NewReplacer(`[`, ``, `]`, ``, `"`, ``).Replace(raw)
	stripped = strings.ReplaceAll(stripped, ",", ", ")
	return strings.TrimSpace(stripped)
}
