package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Marker labels delimit the auto-generated matrix section in README.md.
//
// Marker 标签界定 README.md 中自动生成的矩阵段。
const (
	MarkerStart = "<!-- COVERAGE-MATRIX:START (generated by `make matrix`; do not edit) -->"
	MarkerEnd   = "<!-- COVERAGE-MATRIX:END -->"
)

// Render produces the markdown body intended to replace the content between the
// MarkerStart and MarkerEnd lines in backend/test/README.md.
//
// Render 渲染欲塞入 README.md 两 Marker 间的 markdown 主体。
func Render(m Matrix) string {
	var b strings.Builder
	s := m.Summarize()

	fmt.Fprintln(&b, MarkerStart)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "> Generated %s by `make matrix`. Run `make audit` to verify.\n",
		time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintln(&b)

	// Section 1: HTTP endpoints
	fmt.Fprintf(&b, "## 1. HTTP endpoints (%d / %d covered, %s)\n",
		s.Endpoints.Covered, s.Endpoints.Total, pct(s.Endpoints.Covered, s.Endpoints.Total))
	fmt.Fprintln(&b)
	renderEndpoints(&b, m.Endpoints)
	fmt.Fprintln(&b)

	// Section 2: Error codes
	fmt.Fprintf(&b, "## 2. Error codes (%d / %d covered, %s)\n",
		s.ErrCodes.Covered, s.ErrCodes.Total, pct(s.ErrCodes.Covered, s.ErrCodes.Total))
	fmt.Fprintln(&b)
	renderErrCodes(&b, m.ErrCodes)
	fmt.Fprintln(&b)

	// Section 3: SSE protocol
	fmt.Fprintf(&b, "## 3. SSE protocol (%d / %d covered, %s)\n",
		s.SSE.Covered, s.SSE.Total, pct(s.SSE.Covered, s.SSE.Total))
	fmt.Fprintln(&b)
	renderSSE(&b, m.SSE)
	fmt.Fprintln(&b)

	// Section 4: Cross seams
	fmt.Fprintf(&b, "## 4. Cross-domain seams (%d / %d covered, %s)\n",
		s.Cross.Covered, s.Cross.Total, pct(s.Cross.Covered, s.Cross.Total))
	fmt.Fprintln(&b)
	renderSeams(&b, m.Cross)
	fmt.Fprintln(&b)

	// Section 5: Lifecycle chains
	fmt.Fprintf(&b, "## 5. Lifecycle chains (%d / %d covered, %s)\n",
		s.Lifecycle.Covered, s.Lifecycle.Total, pct(s.Lifecycle.Covered, s.Lifecycle.Total))
	fmt.Fprintln(&b)
	renderSeams(&b, m.Lifecycle)
	fmt.Fprintln(&b)

	// Summary
	totalCov := s.Endpoints.Covered + s.ErrCodes.Covered + s.SSE.Covered + s.Cross.Covered + s.Lifecycle.Covered
	totalTot := s.Endpoints.Total + s.ErrCodes.Total + s.SSE.Total + s.Cross.Total + s.Lifecycle.Total
	fmt.Fprintln(&b, "## Summary")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "- **Total targets**: %d\n", totalTot)
	fmt.Fprintf(&b, "- **Covered**: %d (%s)\n", totalCov, pct(totalCov, totalTot))
	fmt.Fprintf(&b, "- **Uncovered**: %d\n", totalTot-totalCov)
	if n := len(m.Orphans); n > 0 {
		fmt.Fprintf(&b, "- **Orphan annotations**: %d\n", n)
	}
	if n := len(m.Unannotated); n > 0 {
		fmt.Fprintf(&b, "- **Tests without `// covers:` annotation**: %d\n", n)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, MarkerEnd)

	return b.String()
}

func renderEndpoints(b *strings.Builder, rows []EndpointRow) {
	// Group by domain prefix (the segment after /api/v1/ until next slash).
	// 按 domain(/api/v1/ 后第一段)分组。
	groups := map[string][]EndpointRow{}
	for _, r := range rows {
		d := extractDomain(r.Endpoint.Path)
		groups[d] = append(groups[d], r)
	}
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, d := range keys {
		grp := groups[d]
		covered := 0
		for _, r := range grp {
			if len(r.Tests) > 0 {
				covered++
			}
		}
		mark := badge(covered, len(grp))
		fmt.Fprintf(b, "### %s domain (%d/%d %s)\n", d, covered, len(grp), mark)
		fmt.Fprintln(b)
		fmt.Fprintln(b, "| Method | Path | Test |")
		fmt.Fprintln(b, "|---|---|---|")
		for _, r := range grp {
			method := r.Endpoint.Method
			p := r.Endpoint.Path
			cell := tableCell(r.Tests)
			if cell == "" {
				method = "**" + method + "**"
				p = "**" + p + "**"
				cell = "**❌ uncovered**"
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n", method, p, cell)
		}
		fmt.Fprintln(b)
	}
}

func renderErrCodes(b *strings.Builder, rows []ErrCodeRow) {
	fmt.Fprintln(b, "| Code | HTTP | Test |")
	fmt.Fprintln(b, "|---|---|---|")
	for _, r := range rows {
		code := r.ErrCode.Code
		cell := tableCell(r.Tests)
		if cell == "" {
			code = "**" + code + "**"
			cell = "**❌ uncovered**"
		}
		fmt.Fprintf(b, "| %s | %d | %s |\n", code, r.ErrCode.HTTPStatus, cell)
	}
}

func renderSSE(b *strings.Builder, rows []SSERow) {
	// Group by stream.
	// 按 stream 分组。
	streams := map[string][]SSERow{}
	for _, r := range rows {
		streams[r.SSE.Stream] = append(streams[r.SSE.Stream], r)
	}
	order := []string{"eventlog", "forge", "notifications"}
	for _, s := range order {
		grp, ok := streams[s]
		if !ok {
			continue
		}
		covered := 0
		for _, r := range grp {
			if len(r.Tests) > 0 {
				covered++
			}
		}
		fmt.Fprintf(b, "### %s (%d/%d %s)\n", s, covered, len(grp), badge(covered, len(grp)))
		fmt.Fprintln(b)
		fmt.Fprintln(b, "| Event | Sub | Test |")
		fmt.Fprintln(b, "|---|---|---|")
		for _, r := range grp {
			sub := r.SSE.BlockType
			if sub == "" {
				sub = r.SSE.Kind
			}
			if sub == "" {
				sub = r.SSE.NotifType
			}
			if sub == "" {
				sub = "—"
			}
			ev := r.SSE.Event
			cell := tableCell(r.Tests)
			if cell == "" {
				ev = "**" + ev + "**"
				cell = "**❌ uncovered**"
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n", ev, sub, cell)
		}
		fmt.Fprintln(b)
	}
}

func renderSeams(b *strings.Builder, rows []SeamRow) {
	fmt.Fprintln(b, "| Seam ID | Description | Test |")
	fmt.Fprintln(b, "|---|---|---|")
	for _, r := range rows {
		id := r.Seam.ID
		cell := tableCell(r.Tests)
		if cell == "" {
			id = "**" + id + "**"
			cell = "**❌ uncovered**"
		}
		fmt.Fprintf(b, "| %s | %s | %s |\n", id, r.Seam.Description, cell)
	}
}

// tableCell formats a list of test references; empty when no tests.
//
// tableCell 把测试引用列表格式化为表格单元;空时返空串。
func tableCell(tests []string) string {
	if len(tests) == 0 {
		return ""
	}
	if len(tests) <= 2 {
		return strings.Join(tests, "; ")
	}
	return fmt.Sprintf("%s; …(+%d)", strings.Join(tests[:2], "; "), len(tests)-2)
}

// pct formats a fraction as a percentage string.
//
// pct 把分数格式化成百分比字符串。
func pct(n, total int) string {
	if total == 0 {
		return "—"
	}
	p := float64(n) * 100 / float64(total)
	return fmt.Sprintf("%.0f%%", p)
}

// badge returns ✅ when fully covered, otherwise an empty string.
//
// badge 全覆盖返 ✅,否则空。
func badge(n, total int) string {
	if total > 0 && n == total {
		return "✅"
	}
	if n == 0 {
		return "❌"
	}
	return "⚠️"
}

// extractDomain returns the first /api/v1/ segment of a path; "other" otherwise.
//
// extractDomain 提取 /api/v1/ 后的第一段;否则返 "other"。
func extractDomain(path string) string {
	const prefix = "/api/v1/"
	if !strings.HasPrefix(path, prefix) {
		return "other"
	}
	rest := path[len(prefix):]
	if i := strings.Index(rest, "/"); i >= 0 {
		rest = rest[:i]
	}
	if i := strings.Index(rest, ":"); i >= 0 {
		rest = rest[:i]
	}
	return rest
}
