// rpc.go — System composes the Python class string from VersionDraft +
// produces the driver template. Driver is identical across handlers (it's
// the JSON-line RPC dispatcher that imports user_handler.HandlerImpl).
//
// Both strings are written to the sandboxed handler's versions/<vID>/ dir
// before SpawnLongLived; the subprocess `python driver.py` imports the user
// class and serves RPC over stdin/stdout.
//
// rpc.go —— 系统从 VersionDraft 拼 Python class 字符串 + driver 模板。
// driver 全 handler 一致(JSON-line RPC 派发器,import user_handler.HandlerImpl)。
// spawn 前两个文件落到 versions/<vID>/,子进程 `python driver.py`。

package handler

import (
	"fmt"
	"strings"

	handlerdomain "github.com/sunweilin/forgify/backend/internal/domain/handler"
)

// AssembleClass produces the user_handler.py contents from a VersionDraft.
// Layout (mirrors spec/03-handler.md §5.1):
//
//	<Imports>
//
//	class HandlerImpl:
//	    def __init__(self, **init_args):
//	        <InitBody>
//	    def shutdown(self):
//	        <ShutdownBody>     # or `pass` if not provided
//	    def <m1.Name>(self, **args):
//	        <m1.Body>
//	    ... per method
//
// Indentation: each body is reindented to 8 spaces (method body is inside
// the class, which adds 4, plus the def line adds another 4).
//
// AssembleClass 从 VersionDraft 生成 user_handler.py。布局见 spec §5.1;
// body 缩进 8 空格(class 体 4 + def 体 4)。
func AssembleClass(d *VersionDraft) string {
	var b strings.Builder
	b.WriteString("# Auto-assembled by Forgify from ops; do not edit by hand.\n")
	if d.Imports != "" {
		b.WriteString(d.Imports)
		if !strings.HasSuffix(d.Imports, "\n") {
			b.WriteByte('\n')
		}
		b.WriteByte('\n')
	}
	b.WriteString("class HandlerImpl:\n")

	// __init__
	b.WriteString("    def __init__(self, **init_args):\n")
	if d.InitBody == "" {
		b.WriteString("        pass\n")
	} else {
		writeIndented(&b, d.InitBody, "        ")
	}
	b.WriteByte('\n')

	// shutdown
	b.WriteString("    def shutdown(self):\n")
	if d.ShutdownBody == "" {
		b.WriteString("        pass\n")
	} else {
		writeIndented(&b, d.ShutdownBody, "        ")
	}
	b.WriteByte('\n')

	// Methods
	for _, m := range d.Methods {
		writeMethod(&b, m)
		b.WriteByte('\n')
	}
	return b.String()
}

// writeMethod writes one `def <name>(self, **args): <body>` block.
//
// writeMethod 写一个 `def <name>(self, **args): <body>` 块。
func writeMethod(b *strings.Builder, m handlerdomain.MethodSpec) {
	fmt.Fprintf(b, "    def %s(self, **args):\n", m.Name)
	if m.Body == "" {
		b.WriteString("        pass\n")
		return
	}
	writeIndented(b, m.Body, "        ")
}

// writeIndented writes each non-empty line of src prefixed with indent.
// Blank lines stay blank (no trailing whitespace).
//
// writeIndented 每非空行加 indent;空行保空。
func writeIndented(b *strings.Builder, src, indent string) {
	for _, line := range strings.Split(src, "\n") {
		if line == "" {
			b.WriteByte('\n')
			continue
		}
		b.WriteString(indent)
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

// DriverScript is the constant Python driver that serves the JSON-line RPC
// protocol (matches spec/03-handler.md §5.5). Identical across handlers;
// the user's HandlerImpl is imported at module level.
//
// DriverScript 是恒定的 Python driver(JSON-line RPC 派发器,spec §5.5)。
// 全 handler 一致;user 的 HandlerImpl module 级 import。
const DriverScript = `# Auto-generated by Forgify; do not edit.
import sys, json, traceback
from user_handler import HandlerImpl


def respond(payload):
    sys.stdout.write(json.dumps(payload) + "\n")
    sys.stdout.flush()


def main():
    # init
    init_line = sys.stdin.readline()
    if not init_line:
        return
    init_msg = json.loads(init_line)
    try:
        handler = HandlerImpl(**init_msg.get("args", {}))
        respond({"type": "ready"})
    except Exception as e:
        respond({
            "type": "init_error",
            "error": str(e),
            "trace": traceback.format_exc(),
        })
        return

    # message loop
    for line in sys.stdin:
        if not line.strip():
            continue
        msg = json.loads(line)
        msg_type = msg.get("type")
        if msg_type == "shutdown":
            try:
                handler.shutdown()
            except Exception:
                pass
            break
        if msg_type == "call":
            request_id = msg["id"]
            method_name = msg["method"]
            args = msg.get("args", {}) or {}
            # private methods (leading underscore) are not LLM-callable
            if method_name.startswith("_"):
                respond({
                    "type": "error",
                    "id": request_id,
                    "error": "private method: " + method_name,
                    "trace": "",
                })
                continue
            try:
                method = getattr(handler, method_name)
            except AttributeError:
                respond({
                    "type": "error",
                    "id": request_id,
                    "error": "no such method: " + method_name,
                    "trace": "",
                })
                continue
            try:
                result = method(**args)
                # generator → progress + final
                if hasattr(result, "__iter__") and not isinstance(result, (str, bytes, list, dict)):
                    final = None
                    for item in result:
                        if isinstance(item, dict) and "progress" in item:
                            respond({"type": "progress", "id": request_id, "data": item["progress"]})
                        else:
                            final = item
                    respond({"type": "return", "id": request_id, "data": final})
                else:
                    respond({"type": "return", "id": request_id, "data": result})
            except Exception as e:
                respond({
                    "type": "error",
                    "id": request_id,
                    "error": str(e),
                    "trace": traceback.format_exc(),
                })


if __name__ == "__main__":
    main()
`
