export const qk = {
  health: () => ["health"] as const,
  conversations: (filter?: { archived?: boolean }) => ["conversations", filter] as const,
  conversation: (id: string) => ["conversation", id] as const,
  messages: (convId: string) => ["messages", convId] as const,

  users: () => ["users"] as const,

  apikeys: () => ["api-keys"] as const,
  providers: () => ["providers"] as const,
  scenarios: () => ["scenarios"] as const,
  modelConfigs: () => ["model-configs"] as const,

  functions: () => ["functions"] as const,
  function: (id: string) => ["function", id] as const,
  functionVersions: (id: string) => ["function-versions", id] as const,
  functionExecutions: (id: string) => ["function-executions", id] as const,
  handlers: () => ["handlers"] as const,
  handler: (id: string) => ["handler", id] as const,
  handlerVersions: (id: string) => ["handler-versions", id] as const,
  handlerCalls: (id: string) => ["handler-calls", id] as const,
  handlerConfig: (id: string) => ["handler-config", id] as const,
  workflows: () => ["workflows"] as const,
  workflow: (id: string) => ["workflow", id] as const,
  workflowVersions: (id: string) => ["workflow-versions", id] as const,
  agents: () => ["agents"] as const,
  agent: (id: string) => ["agent", id] as const,
  agentVersions: (id: string) => ["agent-versions", id] as const,
  agentExecutions: (id: string) => ["agent-executions", id] as const,

  flowruns: (filter?: Record<string, unknown>) => ["flowruns", filter] as const,
  flowrun: (id: string) => ["flowrun", id] as const,
  flowrunNodes: (id: string) => ["flowrun-nodes", id] as const,
  triggers: () => ["triggers"] as const,

  catalog: () => ["catalog"] as const,
  notificationsSnap: () => ["notifications-snapshot"] as const,

  skills: () => ["skills"] as const,
  skill: (name: string) => ["skill", name] as const,
  mcpServers: () => ["mcp-servers"] as const,
  memories: (type?: string) => ["memories", type ?? "all"] as const,
  documents: () => ["documents"] as const,
  documentsTree: () => ["documents-tree"] as const,
  document: (id: string) => ["document", id] as const,
  sandboxRuntimes: () => ["sandbox-runtimes"] as const,
  sandboxEnvs: () => ["sandbox-envs"] as const,
  permissions: () => ["permissions"] as const,
  llmHealth: () => ["llm-health"] as const,

  devInfo: () => ["dev-info"] as const,
  devRuntime: () => ["dev-runtime"] as const,
  devRoutes: () => ["dev-routes"] as const,
  devForgifyHome: () => ["dev-forgify-home"] as const,
  devBashProcesses: () => ["dev-bash-processes"] as const,
  llmTrace: () => ["llm-trace"] as const,
  lastPrompt: () => ["dev-last-prompt"] as const,
} as const;
