import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, '..', 'dist', 'index.html');
const b = await chromium.launch();
const p = await b.newPage();
p.on('console', (m) => console.log('[console.' + m.type() + ']', m.text()));
p.on('pageerror', (e) => console.log('[pageerror]', e.message, '\n', e.stack?.split('\n').slice(0,4).join('\n')));
await p.goto('file://' + dist);
await p.waitForTimeout(2500);
const ok = await p.evaluate(() => !!(window.docEditor));
console.log('docEditor ready:', ok);
await b.close();
