// Package catalog is the domain layer for the Capability Catalog —
// a derived (not source-of-truth) summary of every available capability
// (forge, skill, mcp, future) injected into chat's system prompt so the
// LLM knows what it can do at a category level + how to pick between
// overlapping options.
//
// The catalog is built by polling each registered CatalogSource on a
// 1s tick (no event subscription — fingerprint short-circuits the LLM
// call when nothing changed). On change, an LLM-driven Generator emits
// a prose summary; if generation fails, a mechanical fallback enumerates
// per-source so the system prompt is always populated.
//
// Per catalog.md design:
//   - rm ~/.forgify/.catalog.json reconstructs from sources (no data loss)
//   - sources implement CatalogSource (Name + Granularity + ListItems)
//   - subagent does NOT implement this — Subagent tool's own description
//     already covers the subagent-type list; catalog re-listing is
//     redundant
//
// Layering (per CLAUDE.md §S13):
//
//	internal/domain/catalog/catalog.go     — entities + 2 sentinels (this file)
//	internal/domain/catalog/source.go      — CatalogSource port + Granularity
//	internal/app/catalog/                  — Service / Generator / pollLoop (D8-2/D8-3)
//	internal/app/{forge,skill,mcp}/catalogsource.go — port impls (D8-4)
//	internal/transport/httpapi/handlers/catalog.go  — 2 HTTP endpoints (D8-6)
//
// Aliases:
//
//	catalogdomain "…/internal/domain/catalog"
//	catalogapp    "…/internal/app/catalog"
//
// Package catalog 是 Capability Catalog 的 domain 层——所有能力（forge /
// skill / mcp / 未来）的派生汇总（非 source of truth），注入 chat 的
// system prompt 让 LLM 在类目层知道有什么 + 如何在重叠选项中取舍。
//
// catalog 由 1s tick 轮询各 CatalogSource 构建（不订阅事件——fingerprint
// 在数据未变时短路 LLM 调用）。变更时 LLM-driven Generator 产 prose
// summary；失败时 mechanical fallback per-source 枚举保证 system prompt 永
// 有内容。
package catalog

import (
	"errors"
	"time"
)

// Catalog is the derived view that gets injected into chat system prompts.
// Built by app/catalog.Service from registered CatalogSources; never
// hand-edited. Persisted to ~/.forgify/.catalog.json as a cold-start
// optimization (the in-memory cache is the read-path source of truth).
//
// Catalog 是注入 chat system prompt 的派生视图。app/catalog.Service 从注
// 册的 CatalogSource 构建；不手编。落到 ~/.forgify/.catalog.json 作 cold-
// start 优化（内存 cache 才是读路径事实源）。
type Catalog struct {
	// Summary is the human-readable text that goes into the system prompt
	// (~500 token target). When generated by LLM, may include a "Notes on
	// choosing" section with routing observations across overlapping
	// capabilities.
	//
	// Summary 是进 system prompt 的人类可读文本（~500 token 目标）。LLM
	// 生成时可含跨重叠能力的"Notes on choosing"路由观察段。
	Summary string `json:"summary"`

	// Coverage maps source name → list of item IDs the Summary covered.
	// Validates Generator output completeness; never trimmed (we want
	// to know the LLM didn't drop items even when it merged them in
	// the prose).
	//
	// Coverage：source 名 → Summary 覆盖的 item ID 列表。校验 Generator
	// 完整性；从不裁剪（即使 LLM 合并到 prose 里也要知道它没漏掉）。
	Coverage map[string][]string `json:"coverage"`

	// Fingerprint is sha256 of sorted (source + name + description) of
	// the items used. lastFP=this means "polling tick can short-circuit;
	// no source changed since last regen".
	//
	// Fingerprint：用过的 items 的 sorted (source + name + description)
	// 的 sha256。lastFP=this 表示 polling tick 可短路（自上次 regen 起无
	// source 变化）。
	Fingerprint string `json:"fingerprint"`

	// GeneratedAt is when the regen completed (LLM or mechanical).
	//
	// GeneratedAt：regen 完成时间（LLM 或 mechanical）。
	GeneratedAt time.Time `json:"generatedAt"`

	// Version increments on each successful write — useful for the
	// /dev console and for future client-side cache validation.
	//
	// Version：每次成功写自增——给 /dev console + 未来 client cache 校验。
	Version int `json:"version"`

	// SourcesAt records when each source was last successfully polled.
	// Different sources can have different timestamps if a source was
	// transiently failing.
	//
	// SourcesAt：每个 source 最后一次成功 poll 的时间。某 source 瞬时失败
	// 时各 source 时间戳可不同。
	SourcesAt map[string]time.Time `json:"sourcesAt"`

	// GeneratedBy is "llm" or "mechanical-fallback". Lets debug-time
	// readers tell whether the prose was AI-written or auto-enumerated.
	//
	// GeneratedBy："llm" 或 "mechanical-fallback"。让 debug 时读者知道
	// prose 是 AI 写还是自动枚举。
	GeneratedBy string `json:"generatedBy"`
}

// Sentinel errors per catalog.md §10. Both are internally consumed
// (retry / mechanical fallback) — neither should reach the HTTP handler,
// so neither is registered in transport/httpapi/response/errmap.go.
//
// Sentinel 错误（catalog.md §10）。两个都内部消化（重试 / mechanical
// fallback）——都不该到达 HTTP handler，故都不进 errmap。
var (
	// ErrCoverageIncomplete signals the LLM generator output dropped one
	// or more source items even after retries. Caller (Service.Refresh)
	// reacts by switching to mechanicalFallback.
	//
	// ErrCoverageIncomplete：LLM generator 重试后仍漏掉至少一个 source
	// item。调用方（Service.Refresh）切 mechanicalFallback。
	ErrCoverageIncomplete = errors.New("catalog: generator output missing items")

	// ErrGenerationFailed wraps lower-level LLM transport / decode
	// failures (network, JSON parse, no working API key). Same fallback
	// contract as ErrCoverageIncomplete.
	//
	// ErrGenerationFailed wrap 底层 LLM 传输 / 解码失败（网络、JSON
	// parse、无可用 API key）。fallback 契约同 ErrCoverageIncomplete。
	ErrGenerationFailed = errors.New("catalog: LLM generation failed")

	// ErrAllSourcesFailed is returned by Service.Refresh when every
	// configured catalog source errored, leaving no items at all to
	// generate from. Reachable via POST /api/v1/catalog:refresh; without
	// a sentinel this hits "unmapped domain error" → 500. Mapped to
	// 503 in errmap.go since this is "service degraded, no data
	// available" (transient — retry later).
	//
	// ErrAllSourcesFailed Service.Refresh 在所有 source 都报错（无任何
	// item 可生成）时返回。POST /api/v1/catalog:refresh 触达；无
	// sentinel 触发 unmapped 警报。errmap 映射 503（服务降级，无可用
	// 数据；可重试）。
	ErrAllSourcesFailed = errors.New("catalog: all sources failed; previous cache retained")
)

// SystemPromptProvider is the narrow interface chat.runner consumes to
// fetch the catalog text without depending on the full app/catalog
// package (avoids an import cycle if catalog ever needs chat domain
// types). Service implements this; chat consumes it via setter
// injection.
//
// SystemPromptProvider 是 chat.runner 取 catalog 文本的窄接口，不依赖
// 完整 app/catalog 包（防 catalog 未来需 chat domain 类型时循环 import）。
// Service 实现；chat 经 setter 注入消费。
type SystemPromptProvider interface {
	// GetForSystemPrompt returns the cached catalog Summary (already
	// formatted for direct prepend into system prompt). Empty string
	// when no catalog has been built yet (boot window) — caller should
	// silently skip the section.
	//
	// GetForSystemPrompt 返缓存 catalog Summary（已格式化可直接前置 system
	// prompt）。catalog 还没构造时返空（boot 窗口）——调用方应静默跳过。
	GetForSystemPrompt() string
}
