import 'dart:collection';

import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../model/status_state.dart';

/// The two visual grammars supported by the chrome-band stage. 顶带舞台支持的两种视觉语法。
enum NoticeKind { pill, approval }

/// Where a message came from. This is intentionally presentation-only: durable event truth still
/// lives in the notification repository / left tray; operation feedback never enters that ledger.
/// 消息来源只描述展示副本:持久事件真相仍在通知仓库/左岛,操作反馈绝不写入该账本。
enum NoticeOrigin { operation, event, system }

/// Pending-lane priority. Priority changes only who comes NEXT; it never replaces the visible card.
/// 候场优先级只决定下一位,绝不顶掉正在显示的卡。
enum NoticePriority { normal, priority }

/// A presentation copy accepted by the shared top-band message center. It deliberately contains no
/// notification-repository handle: clearing the stage therefore cannot mark a row read, delete an
/// inbox item, or decide an approval. 统一顶带消息中心接收的展示副本;刻意不持通知仓库句柄,所以清舞台
/// 在结构上就不可能标已读、删左岛行或替用户审批。
@immutable
class NoticeMessage {
  const NoticeMessage({
    required this.text,
    this.icon,
    this.tone = AnTone.none,
    this.location,
    this.kind = NoticeKind.pill,
    this.origin = NoticeOrigin.operation,
    this.title,
    this.flowrunId,
    this.nodeId,
    this.coalesceKey,
  });

  final String text;
  final IconData? icon;
  final AnTone tone;

  /// Optional deep-link location. null means the message has no "View" action. 可选深链。
  final String? location;
  final NoticeKind kind;
  final NoticeOrigin origin;

  /// Approval-block display / addressing data. The app assembly layer resolves the real parked node;
  /// core never imports a feature repository. 审批块显示/寻址数据;真节点由 app 装配层解析。
  final String? title;
  final String? flowrunId;
  final String? nodeId;

  /// Optional identity for noisy operation paths (for example repeated autosave failures). While one
  /// matching copy is visible or pending, another is ignored in O(1); once it leaves, a later real
  /// occurrence may surface again. 可选合并身份:同类在显/候场时 O(1) 去重,离场后可再次出现。
  final String? coalesceKey;
}

/// One staged entry. [id] is generated by the center and guards every delayed animation callback.
/// 一条舞台项;中心生成的 id 守住所有延迟动画回调。
@immutable
class NoticeEntry {
  const NoticeEntry({
    required this.id,
    required this.sequence,
    required this.message,
    this.dismissRequested = false,
    this.briskPlayback = false,
  });

  final String id;
  final int sequence;
  final NoticeMessage message;

  /// The controller keeps a clearing/current card mounted while asking it to play its reverse line.
  /// 控制器清场时仍挂住当前卡,只请求它倒放退场。
  final bool dismissRequested;

  /// Promoted while more real messages remain: use the shorter readable dwell, never an instant skip.
  /// 上台时仍有真实积压:用较短但可读的驻留,绝不瞬跳。
  final bool briskPlayback;

  NoticeEntry requestDismiss() => dismissRequested
      ? this
      : NoticeEntry(
          id: id,
          sequence: sequence,
          message: message,
          dismissRequested: true,
          briskPlayback: briskPlayback,
        );

  NoticeEntry withBriskPlayback(bool value) => value == briskPlayback
      ? this
      : NoticeEntry(
          id: id,
          sequence: sequence,
          message: message,
          dismissRequested: dismissRequested,
          briskPlayback: value,
        );
}

/// A constant-size visual hint for one pending message. No text is exposed or laid out until it is
/// promoted. 候场消息的常量级视觉提示;上台前不暴露/排版正文。
@immutable
class NoticeCue {
  const NoticeCue({required this.id, required this.tone, required this.kind});

  final String id;
  final AnTone tone;
  final NoticeKind kind;
}

/// The entire pending projection consumed by the tail. [cues] is always length 0..2, regardless of
/// whether the private queue contains two or twenty thousand entries. 尾巴消费的完整投影;cues 永远
/// 只有 0..2 项,私有队列无论 2 条还是 2 万条都不膨胀 UI state。
@immutable
class NoticeQueueSummary {
  const NoticeQueueSummary({
    this.cues = const <NoticeCue>[],
    this.pendingCount = 0,
    this.latestSequence = 0,
  });

  final List<NoticeCue> cues;
  final int pendingCount;
  final int latestSequence;

  int get overflowCount => pendingCount > 2 ? pendingCount - 2 : 0;
  bool get hasBulkClear => overflowCount > 0;
}

@immutable
class NoticeCenterState {
  const NoticeCenterState({
    this.current,
    this.queue = const NoticeQueueSummary(),
  });

  final NoticeEntry? current;
  final NoticeQueueSummary queue;
}

/// The shared top-band message center.
///
/// Internally it owns two [ListQueue]s (O(1) enqueue/dequeue). Riverpod sees only the fixed projection
/// above, so a burst never copies or rebuilds the backlog. Priority entries (approvals and user
/// operation feedback) wait in FIFO order ahead of normal event notices, but the current card is
/// sacred: no arrival may preempt it.
///
/// 统一顶带消息中心。内部双 ListQueue 常数时间进出;Riverpod 只见定长投影,风暴不复制/重建积压。
/// 审批/操作反馈在 priority 候场 FIFO,排在普通事件前,但当前卡神圣不可抢占。
class NoticeCenter extends Notifier<NoticeCenterState> {
  /// Priority stays responsive without starving durable normal events under a continuous operation
  /// stream: after three priority promotions, one waiting normal entry gets the stage. 优先仍利落,但连续
  /// 操作流下每三条须让一条 normal 上台,「不丢」也包含最终可见。
  static const int priorityBurstLimit = 3;

  ListQueue<NoticeEntry> _priorityPending = ListQueue<NoticeEntry>();
  ListQueue<NoticeEntry> _normalPending = ListQueue<NoticeEntry>();
  Map<String, String> _activeCoalesce = <String, String>{};
  NoticeEntry? _current;
  int _sequence = 0;
  int _priorityStreak = 0;

  @override
  NoticeCenterState build() => const NoticeCenterState();

  /// Convenience entry point for operation/system feedback. Operation feedback is priority by
  /// default so it does not sit behind a long event backlog, but it still never interrupts current.
  /// 操作/系统反馈糖口;默认进优先候场,避免埋在事件积压后,但仍不打断当前卡。
  String show(
    String text, {
    IconData? icon,
    AnTone tone = AnTone.none,
    String? location,
    NoticeOrigin origin = NoticeOrigin.operation,
    String? coalesceKey,
    NoticePriority priority = NoticePriority.priority,
  }) => push(
    NoticeMessage(
      text: text,
      icon: icon,
      tone: tone,
      location: location,
      origin: origin,
      coalesceKey: coalesceKey,
    ),
    priority: priority,
  );

  /// Enqueue a message without ever dropping an older one. Returns the generated id; when a matching
  /// [NoticeMessage.coalesceKey] is already active, returns that existing id and does not enqueue.
  /// 入队且永不丢旧消息;合并身份已在场时返回原 id,不重复入队。
  String push(
    NoticeMessage message, {
    NoticePriority priority = NoticePriority.normal,
  }) {
    final coalesceKey = message.coalesceKey;
    if (coalesceKey != null) {
      final existing = _activeCoalesce[coalesceKey];
      if (existing != null) return existing;
    }

    final sequence = ++_sequence;
    final entry = NoticeEntry(
      id: 'notice_$sequence',
      sequence: sequence,
      message: message,
    );
    if (coalesceKey != null) _activeCoalesce[coalesceKey] = entry.id;

    if (_current == null) {
      _current = entry;
    } else if (priority == NoticePriority.priority) {
      _priorityPending.addLast(entry);
    } else {
      _normalPending.addLast(entry);
    }
    _publish();
    return entry.id;
  }

  /// Ask the current widget to play its exit. Identity guarding makes stale close/tap callbacks inert.
  /// 请求当前件退场;id 守卫让旧关闭/点击回调完全惰性。
  void dismissCurrent(String id) {
    final current = _current;
    if (current == null || current.id != id || current.dismissRequested) return;
    _current = current.requestDismiss();
    _publish();
  }

  /// Complete an exit and promote exactly one next entry. Called only after the visual reverse ends.
  /// 完成退场并只递补一条;仅在视觉倒放结束后调用。
  void finishExit(String id) {
    final current = _current;
    if (current == null || current.id != id) return;
    _releaseCoalesce(current);
    _current = _takeNext();
    _publish();
  }

  /// Clear the visible snapshot selected by the `+N → X` affordance.
  ///
  /// The pending queues are synchronously swapped out and the current card remains mounted with a
  /// dismiss request. Any arrival after this call enters the fresh queues and survives the old card's
  /// animation. This state owns presentation copies only; the left tray / unread / approval truth is
  /// structurally untouched. `+N→X` 的快照清场:同步换掉候场队列,当前卡带退场请求继续挂载;调用后
  /// 新到消息进入新队列,不会被旧卡动画误删。这里只持展示副本,左岛/未读/审批真相结构性不受影响。
  void clearVisibleSnapshot() {
    final current = _current;
    if (current == null) return;

    _priorityPending = ListQueue<NoticeEntry>();
    _normalPending = ListQueue<NoticeEntry>();
    _priorityStreak = 0;
    final currentCoalesce = current.message.coalesceKey;
    _activeCoalesce = currentCoalesce == null
        ? <String, String>{}
        : <String, String>{currentCoalesce: current.id};
    _current = current.requestDismiss();
    _publish();
  }

  NoticeEntry? _takeNext() {
    final NoticeEntry? next;
    if (_priorityPending.isNotEmpty &&
        (_normalPending.isEmpty || _priorityStreak < priorityBurstLimit)) {
      next = _priorityPending.removeFirst();
      // Priorities shown while no normal waits do not consume the fairness budget. 无 normal 候场时
      // 不消耗公平预算;normal 一到仍可享完整三条优先突发。
      _priorityStreak = _normalPending.isEmpty ? 0 : _priorityStreak + 1;
    } else if (_normalPending.isNotEmpty) {
      next = _normalPending.removeFirst();
      _priorityStreak = 0;
    } else {
      next = null;
      _priorityStreak = 0;
    }
    return next?.withBriskPlayback(
      _priorityPending.isNotEmpty || _normalPending.isNotEmpty,
    );
  }

  void _releaseCoalesce(NoticeEntry entry) {
    final key = entry.message.coalesceKey;
    if (key != null && _activeCoalesce[key] == entry.id) {
      _activeCoalesce.remove(key);
    }
  }

  void _publish() {
    final cues = <NoticeCue>[];
    void take(Iterable<NoticeEntry> queue) {
      for (final entry in queue) {
        if (cues.length == 2) return;
        cues.add(
          NoticeCue(
            id: entry.id,
            tone: entry.message.tone,
            kind: entry.message.kind,
          ),
        );
      }
    }

    take(_priorityPending);
    if (cues.length < 2) take(_normalPending);
    state = NoticeCenterState(
      current: _current,
      queue: NoticeQueueSummary(
        cues: List<NoticeCue>.unmodifiable(cues),
        pendingCount: _priorityPending.length + _normalPending.length,
        latestSequence: _sequence,
      ),
    );
  }
}

final noticeCenterProvider = NotifierProvider<NoticeCenter, NoticeCenterState>(
  NoticeCenter.new,
);
