// workflow_media_test.go — WRK-082 批B' 的验收场景:媒体真的跨 workflow 节点流动。
//
// 这是不变量①②③在真二进制上的合流证明:上游 agent 节点用挂载的 `sys:generate_image` 画一张图
// (产出咽喉出 MediaRef receipt)、把 receipt 当自己的终答交出去(节点结果),下游 agent 节点经
// CEL 拿到它,而**消费咽喉**在装配它的历史时把引用解成原生 image part——于是下游模型**真的看见
// 了像素**,以线缆上的 base64 为证。这一条断言链是「四不变量成立」与「四个漂亮的接口」之间的
// 全部差别。
//
// workflow_media_test.go — the 批B' acceptance scenario: media really crosses workflow nodes.
package scenarios

import (
	"encoding/base64"
	"regexp"
	"strings"
	"testing"

	"github.com/sunweilin/anselm/testend/harness"
)

// attIDShape 是 MediaRef 文法的 id 形(与后端 pkg/mediaref 同款),黑盒侧只认这个形。
var attIDShape = regexp.MustCompile(`att_[0-9a-f]{16}`)

// TestWorkflowMedia_AgentNodeToAgentNode: A 画 → A 把 receipt 交出 → B 看见。
func TestWorkflowMedia_AgentNodeToAgentNode(t *testing.T) {
	t.Parallel()
	srv := harness.Start(t)
	mock := harness.NewLLMMock(t)
	c := srv.Client(t)
	wsID := c.POST("/api/v1/workspaces", map[string]any{"name": "wf-media"}).Field(t, "id")
	wc := c.WS(wsID)

	keyID := wc.POST("/api/v1/api-keys", map[string]any{
		"provider": "openai", "displayName": "llmmock", "key": "sk-mock", "baseUrl": mock.URL(),
	}).Field(t, "id")
	wc.POST("/api/v1/api-keys/"+keyID+":test", nil).OK(t, nil)
	// Both agent nodes run on a catalog-known VISION model — the gate the chokepoint honors.
	// 两个 agent 节点都跑目录已知的**视觉**模型——咽喉尊重的正是这道闸。
	wc.PUT("/api/v1/workspaces/"+wsID+"/default-models/agent",
		map[string]any{"apiKeyId": keyID, "modelId": dlgModel}).OK(t, nil)

	painter := agCreate(t, wc, map[string]any{
		"name": "Painter", "description": "draws then hands the artifact on",
		"prompt": "Draw what you are asked, then reply with the tool's receipt verbatim.",
		"tools":  []map[string]any{{"ref": "sys:generate_image", "name": "generate image"}},
	})
	viewer := agCreate(t, wc, map[string]any{
		"name": "Viewer", "description": "looks at what upstream produced",
		"prompt": "Describe the picture you were given.",
	})

	wfID := wfCreate(t, wc, "media_pipe", []map[string]any{
		{"op": "add_node", "node": map[string]any{"id": "start", "kind": "trigger", "ref": "trg_manual"}},
		{"op": "add_node", "node": map[string]any{"id": "paint", "kind": "agent", "ref": painter,
			"input": map[string]any{"task": "start.topic"}}},
		{"op": "add_node", "node": map[string]any{"id": "look", "kind": "agent", "ref": viewer,
			"input": map[string]any{"picture": "paint.text"}}},
		{"op": "add_edge", "edge": map[string]any{"id": "e1", "from": "start", "to": "paint"}},
		{"op": "add_edge", "edge": map[string]any{"id": "e2", "from": "paint", "to": "look"}},
	})

	mock.Enqueue(dlgModel,
		// ① painter 第一步:点名挂载的能力工具。
		harness.LLMTurn{ToolCalls: []harness.MockToolCall{{Name: "generate_image",
			Args: fw(map[string]any{"prompt": "a lighthouse at dusk", "aspect": "square"})}}},
		// ② painter 第二步:把 receipt 抄进终答——这次抄写就是引用抵达下游的方式。
		harness.LLMTurn{EchoLastToolResult: true},
		// ③ viewer:它这时**已经**拿到了像素(下面查线缆)。
		harness.LLMTurn{Text: "I see a lighthouse at dusk."},
	)

	_, status, nodes := runAndWait(t, wc, wfID, map[string]any{"topic": "a lighthouse at dusk"}, 90000)
	if status != "completed" {
		t.Fatalf("media pipeline run must complete, got %s nodes=%s", status, nodes)
	}

	dumps := mock.DumpsFor(dlgModel)
	if len(dumps) < 3 {
		t.Fatalf("want 3 model requests (painter ×2 + viewer), got %d", len(dumps))
	}

	// ① 挂载合成:painter 的工具面恰是那一个能力工具(sys: 前缀真解析成绑定工具)。
	if len(dumps[0].Tools) != 1 || dumps[0].Tools[0] != "generate_image" {
		t.Fatalf("painter's toolset must be exactly its sys: mount, got %v", dumps[0].Tools)
	}

	// ② 产出咽喉:节点结果里带着 receipt(MediaRef 文法的 attachmentId)。receipt 以**字符串**形嵌在
	// 节点结果里(agent 的终答就是文本),故这里按 id 形取——正是消费咽喉在下游要认的那一形。
	m := attIDShape.FindStringSubmatch(string(nodes))
	if m == nil {
		t.Fatalf("node result must carry a well-formed MediaRef: %s", nodes)
	}
	attID := m[0]

	// ③ 消费咽喉——本场景的要害:viewer 的请求里是**原生 image part + 真字节**,不是一句
	// 「上游给了你一张图」的文本。少了这条断言,整条流水线可以全绿而模型什么也没看见。
	viewerRaw := string(dumps[len(dumps)-1].Raw)
	if !strings.Contains(viewerRaw, "image_url") {
		t.Fatalf("downstream agent must receive a native image part, got: %s", truncate(viewerRaw))
	}
	if !strings.Contains(viewerRaw, base64.StdEncoding.EncodeToString(harness.MockPNG)) {
		t.Fatalf("downstream agent's image part must carry the generated bytes: %s", truncate(viewerRaw))
	}

	// ④ 附件是一等公民:下游看到的字节与库里存的逐字节相同。
	content := wc.DoRaw("GET", "/api/v1/attachments/"+attID+"/content", "", nil)
	if content.Status != 200 || string(content.Raw) != string(harness.MockPNG) {
		t.Fatalf("artifact must round-trip byte-exact (HTTP %d, %d bytes)", content.Status, len(content.Raw))
	}
}

// truncate 让失败输出可读——线缆里嵌着 base64 图。
func truncate(s string) string {
	if len(s) > 400 {
		return s[:400] + "…"
	}
	return s
}
